//! Generated by `scripts/generate-css-rule-tests.mjs`; do not edit.
//!
//! Every case is a style sheet and what cssnano makes of it. `kd_css` must give
//! the same, unless the case is listed in `common::DELIBERATE` with both
//! answers.

mod common;

#[test]
fn colours() {
	common::check_all(&[
		("a{color:RED}", "a{color:red}"),
		(".a {\n\tcolor:RED;\n}\n", ".a{color:red}"),
		("a{color:#FF0000}", "a{color:red}"),
		(".a {\n\tcolor:#FF0000;\n}\n", ".a{color:red}"),
		("a{color:#ff0000ff}", "a{color:red}"),
		(".a {\n\tcolor:#ff0000ff;\n}\n", ".a{color:red}"),
		("a{color:#f00f}", "a{color:red}"),
		(".a {\n\tcolor:#f00f;\n}\n", ".a{color:red}"),
		("a{color:#abcdef}", "a{color:#abcdef}"),
		(".a {\n\tcolor:#abcdef;\n}\n", ".a{color:#abcdef}"),
		("a{color:#AABBCC}", "a{color:#abc}"),
		(".a {\n\tcolor:#AABBCC;\n}\n", ".a{color:#abc}"),
		("a{color:rgb(255,0,0)}", "a{color:red}"),
		(".a {\n\tcolor:rgb(255,0,0);\n}\n", ".a{color:red}"),
		("a{color:rgb(255 0 0)}", "a{color:red}"),
		(".a {\n\tcolor:rgb(255 0 0);\n}\n", ".a{color:red}"),
		("a{color:rgb(255 0 0 / 50%)}", "a{color:rgba(255,0,0,.5)}"),
		(
			".a {\n\tcolor:rgb(255 0 0 / 50%);\n}\n",
			".a{color:rgba(255,0,0,.5)}",
		),
		("a{color:rgba(255,0,0,.5)}", "a{color:rgba(255,0,0,.5)}"),
		(
			".a {\n\tcolor:rgba(255,0,0,.5);\n}\n",
			".a{color:rgba(255,0,0,.5)}",
		),
		("a{color:rgba(0,0,0,0)}", "a{color:transparent}"),
		(".a {\n\tcolor:rgba(0,0,0,0);\n}\n", ".a{color:transparent}"),
		("a{color:rgb(10%,20%,30%)}", "a{color:#1a334d}"),
		(".a {\n\tcolor:rgb(10%,20%,30%);\n}\n", ".a{color:#1a334d}"),
		("a{color:rgb(1.5,2.5,3.5)}", "a{color:#020304}"),
		(".a {\n\tcolor:rgb(1.5,2.5,3.5);\n}\n", ".a{color:#020304}"),
		("a{color:hsl(0,100%,50%)}", "a{color:red}"),
		(".a {\n\tcolor:hsl(0,100%,50%);\n}\n", ".a{color:red}"),
		("a{color:hsl(120deg 100% 50%)}", "a{color:#0f0}"),
		(".a {\n\tcolor:hsl(120deg 100% 50%);\n}\n", ".a{color:#0f0}"),
		("a{color:hsla(0,100%,50%,.5)}", "a{color:rgba(255,0,0,.5)}"),
		(
			".a {\n\tcolor:hsla(0,100%,50%,.5);\n}\n",
			".a{color:rgba(255,0,0,.5)}",
		),
		("a{color:hwb(0 0% 0%)}", "a{color:hwb(0 0% 0%)}"),
		(".a {\n\tcolor:hwb(0 0% 0%);\n}\n", ".a{color:hwb(0 0% 0%)}"),
		("a{color:transparent}", "a{color:transparent}"),
		(".a {\n\tcolor:transparent;\n}\n", ".a{color:transparent}"),
		("a{color:white}", "a{color:#fff}"),
		(".a {\n\tcolor:white;\n}\n", ".a{color:#fff}"),
		("a{color:lightgoldenrodyellow}", "a{color:#fafad2}"),
		(
			".a {\n\tcolor:lightgoldenrodyellow;\n}\n",
			".a{color:#fafad2}",
		),
		("a{color:Black}", "a{color:#000}"),
		(".a {\n\tcolor:Black;\n}\n", ".a{color:#000}"),
		("a{color:currentColor}", "a{color:currentColor}"),
		(".a {\n\tcolor:currentColor;\n}\n", ".a{color:currentColor}"),
		("a{color:oklch(0.5 0.2 30)}", "a{color:oklch(.5 .2 30)}"),
		(
			".a {\n\tcolor:oklch(0.5 0.2 30);\n}\n",
			".a{color:oklch(.5 .2 30)}",
		),
		("a{color:lab(50% 20 30)}", "a{color:lab(50% 20 30)}"),
		(
			".a {\n\tcolor:lab(50% 20 30);\n}\n",
			".a{color:lab(50% 20 30)}",
		),
		(
			"a{color:color-mix(in srgb, red 50%, blue)}",
			"a{color:color-mix(in srgb,red 50%,blue)}",
		),
		(
			".a {\n\tcolor:color-mix(in srgb, red 50%, blue);\n}\n",
			".a{color:color-mix(in srgb,red 50%,blue)}",
		),
		("a{color:rgb(300,0,0)}", "a{color:red}"),
		(".a {\n\tcolor:rgb(300,0,0);\n}\n", ".a{color:red}"),
		("a{color:rgb( 255 , 0 , 0 )}", "a{color:red}"),
		(".a {\n\tcolor:rgb( 255 , 0 , 0 );\n}\n", ".a{color:red}"),
		(
			"a{color:rgba(255,255,255,0.5)}",
			"a{color:hsla(0,0%,100%,.5)}",
		),
		(
			".a {\n\tcolor:rgba(255,255,255,0.5);\n}\n",
			".a{color:hsla(0,0%,100%,.5)}",
		),
		("a{color:RGB(0,0,0)}", "a{color:#000}"),
		(".a {\n\tcolor:RGB(0,0,0);\n}\n", ".a{color:#000}"),
		("a{color:Red!important}", "a{color:red!important}"),
		(
			".a {\n\tcolor:Red!important;\n}\n",
			".a{color:red!important}",
		),
		(
			"a{background:RED url(a.png)}",
			"a{background:red url(a.png)}",
		),
		(
			".a {\n\tbackground:RED url(a.png);\n}\n",
			".a{background:red url(a.png)}",
		),
		("a{border:1px solid #FF0000}", "a{border:1px solid red}"),
		(
			".a {\n\tborder:1px solid #FF0000;\n}\n",
			".a{border:1px solid red}",
		),
		("a{box-shadow:0 0 0 1px RED}", "a{box-shadow:0 0 0 1px red}"),
		(
			".a {\n\tbox-shadow:0 0 0 1px RED;\n}\n",
			".a{box-shadow:0 0 0 1px red}",
		),
		(
			"a{filter:drop-shadow(0 0 1px #FFFFFF)}",
			"a{filter:drop-shadow(0 0 1px #FFFFFF)}",
		),
		(
			".a {\n\tfilter:drop-shadow(0 0 1px #FFFFFF);\n}\n",
			".a{filter:drop-shadow(0 0 1px #FFFFFF)}",
		),
		("a{font:12px RED}", "a{font:12px RED}"),
		(".a {\n\tfont:12px RED;\n}\n", ".a{font:12px RED}"),
		("a{animation-name:tan}", "a{animation-name:tan}"),
		(".a {\n\tanimation-name:tan;\n}\n", ".a{animation-name:tan}"),
		("a{grid-area:gold}", "a{grid-area:gold}"),
		(".a {\n\tgrid-area:gold;\n}\n", ".a{grid-area:gold}"),
	]);
}

#[test]
fn numbers() {
	common::check_all(&[
		("a{margin:0px 0em 0rem 0%}", "a{margin:0}"),
		(".a {\n\tmargin:0px 0em 0rem 0%;\n}\n", ".a{margin:0}"),
		("a{margin:0px 0 0px 0}", "a{margin:0}"),
		(".a {\n\tmargin:0px 0 0px 0;\n}\n", ".a{margin:0}"),
		("a{margin:1px 2px 1px 2px}", "a{margin:1px 2px}"),
		(".a {\n\tmargin:1px 2px 1px 2px;\n}\n", ".a{margin:1px 2px}"),
		("a{margin:1px 2px 3px 2px}", "a{margin:1px 2px 3px}"),
		(
			".a {\n\tmargin:1px 2px 3px 2px;\n}\n",
			".a{margin:1px 2px 3px}",
		),
		("a{padding:1px 1px}", "a{padding:1px}"),
		(".a {\n\tpadding:1px 1px;\n}\n", ".a{padding:1px}"),
		("a{padding:1px 2px 1px}", "a{padding:1px 2px}"),
		(".a {\n\tpadding:1px 2px 1px;\n}\n", ".a{padding:1px 2px}"),
		("a{border-width:1px 1px 1px 1px}", "a{border-width:1px}"),
		(
			".a {\n\tborder-width:1px 1px 1px 1px;\n}\n",
			".a{border-width:1px}",
		),
		("a{height:0%}", "a{height:0}"),
		(".a {\n\theight:0%;\n}\n", ".a{height:0}"),
		("a{width:0%}", "a{width:0}"),
		(".a {\n\twidth:0%;\n}\n", ".a{width:0}"),
		(
			"a{width:0.50px;height:+.5px;top:-0.0px;left:00.5em}",
			"a{width:.5px;height:.5px;top:0;left:.5em}",
		),
		(
			".a {\n\twidth:0.50px;\n\theight:+.5px;\n\ttop:-0.0px;\n\tleft:00.5em;\n}\n",
			".a{width:.5px;height:.5px;top:0;left:.5em}",
		),
		(
			"a{width:1.0px;height:1.50px;top:10.0%}",
			"a{width:1px;height:1.5px;top:10%}",
		),
		(
			".a {\n\twidth:1.0px;\n\theight:1.50px;\n\ttop:10.0%;\n}\n",
			".a{width:1px;height:1.5px;top:10%}",
		),
		(
			"a{transition:all 500ms ease;animation-duration:1000ms;transition-delay:0.5s}",
			"a{transition:all .5s ease;animation-duration:1s;transition-delay:.5s}",
		),
		(
			".a {\n\ttransition:all 500ms ease;\n\tanimation-duration:1000ms;\n\ttransition-delay:0.5s;\n}\n",
			".a{transition:all .5s ease;animation-duration:1s;transition-delay:.5s}",
		),
		(
			"a{transform:rotate(360deg);transform:rotate(90deg);transform:rotate(0.5turn)}",
			"a{transform:rotate(1turn);transform:rotate(90deg);transform:rotate(.5turn)}",
		),
		(
			".a {\n\ttransform:rotate(360deg);\n\ttransform:rotate(90deg);\n\ttransform:rotate(0.5turn);\n}\n",
			".a{transform:rotate(1turn);transform:rotate(90deg);transform:rotate(.5turn)}",
		),
		(
			"a{width:calc(10.0px + 0.50em);height:calc(100% - 0px)}",
			"a{width:calc(10px + .5em);height:100%}",
		),
		(
			".a {\n\twidth:calc(10.0px + 0.50em);\n\theight:calc(100% - 0px);\n}\n",
			".a{width:calc(10px + .5em);height:100%}",
		),
		(
			"a{width:calc( 100%   -   20px )}",
			"a{width:calc(100% - 20px)}",
		),
		(
			".a {\n\twidth:calc( 100%   -   20px );\n}\n",
			".a{width:calc(100% - 20px)}",
		),
		(
			"a{opacity:1.5;opacity:-2;opacity:.50}",
			"a{opacity:1;opacity:0;opacity:.5}",
		),
		(
			".a {\n\topacity:1.5;\n\topacity:-2;\n\topacity:.50;\n}\n",
			".a{opacity:1;opacity:0;opacity:.5}",
		),
		(
			"a{line-height:0px;stroke-width:0px;stroke-dashoffset:0px}",
			"a{line-height:0px;stroke-width:0px;stroke-dashoffset:0px}",
		),
		(
			".a {\n\tline-height:0px;\n\tstroke-width:0px;\n\tstroke-dashoffset:0px;\n}\n",
			".a{line-height:0px;stroke-width:0px;stroke-dashoffset:0px}",
		),
		(
			"a{flex:1 1 0%;flex-basis:0px}",
			"a{flex:1 1 0%;flex-basis:0px}",
		),
		(
			".a {\n\tflex:1 1 0%;\n\tflex-basis:0px;\n}\n",
			".a{flex:1 1 0%;flex-basis:0px}",
		),
		("a{z-index:010;font-size:0px}", "a{z-index:10;font-size:0}"),
		(
			".a {\n\tz-index:010;\n\tfont-size:0px;\n}\n",
			".a{z-index:10;font-size:0}",
		),
		(
			"a{margin:1E3px;margin:1e-7px;width:1.5E+3px}",
			"a{margin:1e-7px;width:1500px}",
		),
		(
			".a {\n\tmargin:1E3px;\n\tmargin:1e-7px;\n\twidth:1.5E+3px;\n}\n",
			".a{margin:1e-7px;width:1500px}",
		),
		("a{width:var(--x,0px)}", "a{width:var(--x,0)}"),
		(".a {\n\twidth:var(--x,0px);\n}\n", ".a{width:var(--x,0)}"),
		(
			"a{width:min(0px,1px);width:max(0.50px, 1.0px);width:clamp(0px,1.0px,2px)}",
			"a{width:min(0px,1px);width:max(.5px,1px);width:clamp(0px,1px,2px)}",
		),
		(
			".a {\n\twidth:min(0px,1px);\n\twidth:max(0.50px, 1.0px);\n\twidth:clamp(0px,1.0px,2px);\n}\n",
			".a{width:min(0px,1px);width:max(.5px,1px);width:clamp(0px,1px,2px)}",
		),
		("a{translate:0px 0px}", "a{translate:0 0}"),
		(".a {\n\ttranslate:0px 0px;\n}\n", ".a{translate:0 0}"),
		(
			"a{clip-path:polygon(0% 0%,100% 0%,100% 100%)}",
			"a{clip-path:polygon(0 0,100% 0,100% 100%)}",
		),
		(
			".a {\n\tclip-path:polygon(0% 0%,100% 0%,100% 100%);\n}\n",
			".a{clip-path:polygon(0 0,100% 0,100% 100%)}",
		),
		("a{background-position:0% 0%}", "a{background-position:0 0}"),
		(
			".a {\n\tbackground-position:0% 0%;\n}\n",
			".a{background-position:0 0}",
		),
		("a{border-radius:0% 0%}", "a{border-radius:0 0}"),
		(".a {\n\tborder-radius:0% 0%;\n}\n", ".a{border-radius:0 0}"),
		("a{padding:0%}", "a{padding:0}"),
		(".a {\n\tpadding:0%;\n}\n", ".a{padding:0}"),
		("a{transform:translate(0%,0%)}", "a{transform:translate(0)}"),
		(
			".a {\n\ttransform:translate(0%,0%);\n}\n",
			".a{transform:translate(0)}",
		),
	]);
}

#[test]
fn timing_functions_and_transforms() {
	common::check_all(&[
		(
			"a{transition:opacity .3s cubic-bezier(0.25,0.1,0.25,1)}",
			"a{transition:opacity .3s ease}",
		),
		(
			".a {\n\ttransition:opacity .3s cubic-bezier(0.25,0.1,0.25,1);\n}\n",
			".a{transition:opacity .3s ease}",
		),
		(
			"a{transition:opacity .3s cubic-bezier(0.42,0,1,1)}",
			"a{transition:opacity .3s ease-in}",
		),
		(
			".a {\n\ttransition:opacity .3s cubic-bezier(0.42,0,1,1);\n}\n",
			".a{transition:opacity .3s ease-in}",
		),
		(
			"a{animation:foo 1s steps(1,start) steps(1,end) steps(4,end)}",
			"a{animation:foo step-end steps(4) 1s step-start}",
		),
		(
			".a {\n\tanimation:foo 1s steps(1,start) steps(1,end) steps(4,end);\n}\n",
			".a{animation:foo step-end steps(4) 1s step-start}",
		),
		(
			"a{animation:foo 1s steps(4, jump-end)}",
			"a{animation:foo 1s steps(4)}",
		),
		(
			".a {\n\tanimation:foo 1s steps(4, jump-end);\n}\n",
			".a{animation:foo 1s steps(4)}",
		),
		(
			"a{transform:translate(0,0);transform:translate(10px,0);transform:translate(0,10px);transform:translate3d(0,0,10px)}",
			"a{transform:translate(0);transform:translate(10px);transform:translateY(10px);transform:translateZ(10px)}",
		),
		(
			".a {\n\ttransform:translate(0,0);\n\ttransform:translate(10px,0);\n\ttransform:translate(0,10px);\n\ttransform:translate3d(0,0,10px);\n}\n",
			".a{transform:translate(0);transform:translate(10px);transform:translateY(10px);transform:translateZ(10px)}",
		),
		(
			"a{transform:scale(1,1);transform:scale(2,1);transform:scale(1,2);transform:scale3d(1,1,2)}",
			"a{transform:scale(1);transform:scaleX(2);transform:scaleY(2);transform:scaleZ(2)}",
		),
		(
			".a {\n\ttransform:scale(1,1);\n\ttransform:scale(2,1);\n\ttransform:scale(1,2);\n\ttransform:scale3d(1,1,2);\n}\n",
			".a{transform:scale(1);transform:scaleX(2);transform:scaleY(2);transform:scaleZ(2)}",
		),
		(
			"a{transform:rotateZ(10deg);transform:rotate3d(0,0,1,10deg);transform:rotate3d(1,0,0,10deg)}",
			"a{transform:rotate(10deg);transform:rotateX(10deg)}",
		),
		(
			".a {\n\ttransform:rotateZ(10deg);\n\ttransform:rotate3d(0,0,1,10deg);\n\ttransform:rotate3d(1,0,0,10deg);\n}\n",
			".a{transform:rotate(10deg);transform:rotateX(10deg)}",
		),
		(
			"a{transform:matrix3d(1,0,0,0,0,1,0,0,0,0,1,0,10,20,0,1)}",
			"a{transform:matrix(1,0,0,1,10,20)}",
		),
		(
			".a {\n\ttransform:matrix3d(1,0,0,0,0,1,0,0,0,0,1,0,10,20,0,1);\n}\n",
			".a{transform:matrix(1,0,0,1,10,20)}",
		),
		(
			"a{transform:translate(var(--x),0)}",
			"a{transform:translate(var(--x))}",
		),
		(
			".a {\n\ttransform:translate(var(--x),0);\n}\n",
			".a{transform:translate(var(--x))}",
		),
	]);
}

#[test]
fn urls_and_strings() {
	common::check_all(&[
		("a{background:url( \"a.png\" )}", "a{background:url(a.png)}"),
		(
			".a {\n\tbackground:url( \"a.png\" );\n}\n",
			".a{background:url(a.png)}",
		),
		("a{background:url('a.png')}", "a{background:url(a.png)}"),
		(
			".a {\n\tbackground:url('a.png');\n}\n",
			".a{background:url(a.png)}",
		),
		("a{background:url(a b.png)}", "a{background:url(a b.png)}"),
		(
			".a {\n\tbackground:url(a b.png);\n}\n",
			".a{background:url(a b.png)}",
		),
		(
			"a{background:url(\"a b.png\")}",
			"a{background:url(a\\ b.png)}",
		),
		(
			".a {\n\tbackground:url(\"a b.png\");\n}\n",
			".a{background:url(a\\ b.png)}",
		),
		(
			"a{background:url(\"a(b).png\")}",
			"a{background:url(\"a(b).png\")}",
		),
		(
			".a {\n\tbackground:url(\"a(b).png\");\n}\n",
			".a{background:url(\"a(b).png\")}",
		),
		(
			"a{background:url(./a.png);background:url(a/../b.png)}",
			"a{background:url(a.png);background:url(b.png)}",
		),
		(
			".a {\n\tbackground:url(./a.png);\n\tbackground:url(a/../b.png);\n}\n",
			".a{background:url(a.png);background:url(b.png)}",
		),
		("a{background:url()}", "a{background:url()}"),
		(".a {\n\tbackground:url();\n}\n", ".a{background:url()}"),
		("a{background:url(\"\")}", "a{background:url()}"),
		(".a {\n\tbackground:url(\"\");\n}\n", ".a{background:url()}"),
		(
			"a{background:url(data:image/png;base64,AAA=)}",
			"a{background:url(data:image/png;base64,AAA=)}",
		),
		(
			".a {\n\tbackground:url(data:image/png;base64,AAA=);\n}\n",
			".a{background:url(data:image/png;base64,AAA=)}",
		),
		(
			"a{background:url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg'></svg>\")}",
			"a{background:url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg'></svg>\")}",
		),
		(
			".a {\n\tbackground:url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg'></svg>\");\n}\n",
			".a{background:url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg'></svg>\")}",
		),
		(
			"a{content:'a';content:\"a\\\"b\";content:'a\"b'}",
			"a{content:\"a\";content:'a\"b'}",
		),
		(
			".a {\n\tcontent:'a';\n\tcontent:\"a\\\"b\";\n\tcontent:'a\"b';\n}\n",
			".a{content:\"a\";content:'a\"b'}",
		),
		(
			"a{content:'a\\'b';content:\"\\201C\"}",
			"a{content:\"a'b\";content:\"\\201C\"}",
		),
		(
			".a {\n\tcontent:'a\\'b';\n\tcontent:\"\\201C\";\n}\n",
			".a{content:\"a'b\";content:\"\\201C\"}",
		),
		("a{quotes:'«' '»'}", "a{quotes:\"«\" \"»\"}"),
		(".a {\n\tquotes:'«' '»';\n}\n", ".a{quotes:\"«\" \"»\"}"),
		("a{content:\"a\\\nb\"}", "a{content:\"ab\"}"),
		(".a {\n\tcontent:\"a\\\nb\";\n}\n", ".a{content:\"ab\"}"),
	]);
}

#[test]
fn fonts() {
	common::check_all(&[
		(
			"a{font-family:\"Helvetica Neue\",Arial,sans-serif;font-family:'Open Sans'}",
			"a{font-family:Helvetica Neue,Arial,sans-serif;font-family:Open Sans}",
		),
		(
			".a {\n\tfont-family:\"Helvetica Neue\",Arial,sans-serif;\n\tfont-family:'Open Sans';\n}\n",
			".a{font-family:Helvetica Neue,Arial,sans-serif;font-family:Open Sans}",
		),
		("a{font-family:\"Arial\",\"Arial\"}", "a{font-family:Arial}"),
		(
			".a {\n\tfont-family:\"Arial\",\"Arial\";\n}\n",
			".a{font-family:Arial}",
		),
		("a{font-family:\"1Arial\"}", "a{font-family:\"1Arial\"}"),
		(
			".a {\n\tfont-family:\"1Arial\";\n}\n",
			".a{font-family:\"1Arial\"}",
		),
		(
			"a{font-family:\"Noto Serif JP\",serif}",
			"a{font-family:\"Noto Serif JP\",serif}",
		),
		(
			".a {\n\tfont-family:\"Noto Serif JP\",serif;\n}\n",
			".a{font-family:\"Noto Serif JP\",serif}",
		),
		(
			"a{font-family:monospace,monospace}",
			"a{font-family:monospace,monospace}",
		),
		(
			".a {\n\tfont-family:monospace,monospace;\n}\n",
			".a{font-family:monospace,monospace}",
		),
		(
			"a{font-weight:normal;font-weight:bold;font-weight:BOLD}",
			"a{font-weight:400;font-weight:700}",
		),
		(
			".a {\n\tfont-weight:normal;\n\tfont-weight:bold;\n\tfont-weight:BOLD;\n}\n",
			".a{font-weight:400;font-weight:700}",
		),
		(
			"a{font:normal normal bold 12px/1.5 \"Helvetica Neue\", Arial}",
			"a{font:normal normal 700 12px/1.5 Helvetica Neue,Arial}",
		),
		(
			".a {\n\tfont:normal normal bold 12px/1.5 \"Helvetica Neue\", Arial;\n}\n",
			".a{font:normal normal 700 12px/1.5 Helvetica Neue,Arial}",
		),
		(
			"a{font:italic small-caps bold 12px/30px Georgia,serif}",
			"a{font:italic small-caps 700 12px/30px Georgia,serif}",
		),
		(
			".a {\n\tfont:italic small-caps bold 12px/30px Georgia,serif;\n}\n",
			".a{font:italic small-caps 700 12px/30px Georgia,serif}",
		),
		("a{font:12px/1 var(--f)}", "a{font:12px/1 var(--f)}"),
		(
			".a {\n\tfont:12px/1 var(--f);\n}\n",
			".a{font:12px/1 var(--f)}",
		),
		("a{font:caption}", "a{font:caption}"),
		(".a {\n\tfont:caption;\n}\n", ".a{font:caption}"),
		(
			"a{font-family:\"KaTeX_SansSerif\",serif}",
			"a{font-family:\"KaTeX_SansSerif\",serif}",
		),
		(
			".a {\n\tfont-family:\"KaTeX_SansSerif\",serif;\n}\n",
			".a{font-family:\"KaTeX_SansSerif\",serif}",
		),
		(
			"a{font-family:\"Noto Serif\",\"Serif Pro\",Georgia}",
			"a{font-family:\"Noto Serif\",\"Serif Pro\",Georgia}",
		),
		(
			".a {\n\tfont-family:\"Noto Serif\",\"Serif Pro\",Georgia;\n}\n",
			".a{font-family:\"Noto Serif\",\"Serif Pro\",Georgia}",
		),
	]);
}

#[test]
fn shorthands() {
	common::check_all(&[
		(
			"a{display:block flow;display:inline flow-root;display:block flex;display:list-item block flow}",
			"a{display:block;display:inline-block;display:flex;display:list-item}",
		),
		(
			".a {\n\tdisplay:block flow;\n\tdisplay:inline flow-root;\n\tdisplay:block flex;\n\tdisplay:list-item block flow;\n}\n",
			".a{display:block;display:inline-block;display:flex;display:list-item}",
		),
		(
			"a{background-position:left top;background-position:top left;background-position:center center;background-position:0 0}",
			"a{background-position:50%;background-position:0 0}",
		),
		(
			".a {\n\tbackground-position:left top;\n\tbackground-position:top left;\n\tbackground-position:center center;\n\tbackground-position:0 0;\n}\n",
			".a{background-position:50%;background-position:0 0}",
		),
		(
			"a{background-position:center left;background-position:left center;background-position:left}",
			"a{background-position:0}",
		),
		(
			".a {\n\tbackground-position:center left;\n\tbackground-position:left center;\n\tbackground-position:left;\n}\n",
			".a{background-position:0}",
		),
		(
			"a{background:url(a.png) no-repeat repeat;background-repeat:repeat no-repeat;background-repeat:no-repeat no-repeat}",
			"a{background:url(a.png) repeat-y;background-repeat:repeat-x;background-repeat:no-repeat}",
		),
		(
			".a {\n\tbackground:url(a.png) no-repeat repeat;\n\tbackground-repeat:repeat no-repeat;\n\tbackground-repeat:no-repeat no-repeat;\n}\n",
			".a{background:url(a.png) repeat-y;background-repeat:repeat-x;background-repeat:no-repeat}",
		),
		(
			"a{background:url(a.png) left top / cover no-repeat}",
			"a{background:url(a.png) 0 0/cover no-repeat}",
		),
		(
			".a {\n\tbackground:url(a.png) left top / cover no-repeat;\n}\n",
			".a{background:url(a.png) 0 0/cover no-repeat}",
		),
		(
			"a{unicode-range:U+0025-00FF,u+4??;unicode-range:U+0000-00FF}",
			"a{unicode-range:u+0025-00ff,u+4??;unicode-range:u+00??}",
		),
		(
			".a {\n\tunicode-range:U+0025-00FF,u+4??;\n\tunicode-range:U+0000-00FF;\n}\n",
			".a{unicode-range:u+0025-00ff,u+4??;unicode-range:u+00??}",
		),
		(
			"a{border:1px solid red;border:solid 1px red;border:red 1px solid}",
			"a{border:1px solid red}",
		),
		(
			".a {\n\tborder:1px solid red;\n\tborder:solid 1px red;\n\tborder:red 1px solid;\n}\n",
			".a{border:1px solid red}",
		),
		(
			"a{box-shadow:0 0 1px red inset;box-shadow:inset 0 0 1px red,0 1px 2px blue}",
			"a{box-shadow:inset 0 0 1px red;box-shadow:inset 0 0 1px red,0 1px 2px blue}",
		),
		(
			".a {\n\tbox-shadow:0 0 1px red inset;\n\tbox-shadow:inset 0 0 1px red,0 1px 2px blue;\n}\n",
			".a{box-shadow:inset 0 0 1px red;box-shadow:inset 0 0 1px red,0 1px 2px blue}",
		),
		(
			"a{transition:1s opacity ease-in 2s}",
			"a{transition:opacity 1s ease-in 2s}",
		),
		(
			".a {\n\ttransition:1s opacity ease-in 2s;\n}\n",
			".a{transition:opacity 1s ease-in 2s}",
		),
		(
			"a{animation:2s ease-in 1s infinite alternate both running foo}",
			"a{animation:foo 2s ease-in 1s infinite alternate both running}",
		),
		(
			".a {\n\tanimation:2s ease-in 1s infinite alternate both running foo;\n}\n",
			".a{animation:foo 2s ease-in 1s infinite alternate both running}",
		),
		(
			"a{columns:2 100px;column-rule:1px solid red}",
			"a{columns:100px 2;column-rule:1px solid red}",
		),
		(
			".a {\n\tcolumns:2 100px;\n\tcolumn-rule:1px solid red;\n}\n",
			".a{columns:100px 2;column-rule:1px solid red}",
		),
		(
			"a{flex-flow:wrap row;grid-area:1 / 2 / 3 / 4;grid-row:1/3;grid-column:span 2 / 3}",
			"a{flex-flow:row wrap;grid-area:1/2/3/4;grid-row:1/3;grid-column:span 2/3}",
		),
		(
			".a {\n\tflex-flow:wrap row;\n\tgrid-area:1 / 2 / 3 / 4;\n\tgrid-row:1/3;\n\tgrid-column:span 2 / 3;\n}\n",
			".a{flex-flow:row wrap;grid-area:1/2/3/4;grid-row:1/3;grid-column:span 2/3}",
		),
		(
			"a{grid-template-areas:\"a b\" \"c d\"}",
			"a{grid-template-areas:\"a b\" \"c d\"}",
		),
		(
			".a {\n\tgrid-template-areas:\"a b\" \"c d\";\n}\n",
			".a{grid-template-areas:\"a b\" \"c d\"}",
		),
		(
			"a{grid-template-columns:repeat(auto-fill,minmax(0px,1fr)) [end]}",
			"a{grid-template-columns:repeat(auto-fill,minmax(0,1fr)) [end]}",
		),
		(
			".a {\n\tgrid-template-columns:repeat(auto-fill,minmax(0px,1fr)) [end];\n}\n",
			".a{grid-template-columns:repeat(auto-fill,minmax(0,1fr)) [end]}",
		),
		("a{border:none}", "a{border:none}"),
		(".a {\n\tborder:none;\n}\n", ".a{border:none}"),
		("a{outline:none}", "a{outline:none}"),
		(".a {\n\toutline:none;\n}\n", ".a{outline:none}"),
		("a{border-top:none}", "a{border-top:none}"),
		(".a {\n\tborder-top:none;\n}\n", ".a{border-top:none}"),
		("a{background:none}", "a{background:none}"),
		(".a {\n\tbackground:none;\n}\n", ".a{background:none}"),
		("a{background:transparent}", "a{background:transparent}"),
		(
			".a {\n\tbackground:transparent;\n}\n",
			".a{background:transparent}",
		),
		("a{outline:none!important}", "a{outline:none!important}"),
		(
			".a {\n\toutline:none!important;\n}\n",
			".a{outline:none!important}",
		),
		("a{border:0 none currentColor}", "a{border:0}"),
		(".a {\n\tborder:0 none currentColor;\n}\n", ".a{border:0}"),
		("a{border:1px solid currentColor}", "a{border:1px solid}"),
		(
			".a {\n\tborder:1px solid currentColor;\n}\n",
			".a{border:1px solid}",
		),
		("a{border:medium none}", "a{border:none}"),
		(".a {\n\tborder:medium none;\n}\n", ".a{border:none}"),
	]);
}

#[test]
fn gradients() {
	common::check_all(&[
		(
			"a{background:linear-gradient(to top,red 0%,blue 100%)}",
			"a{background:linear-gradient(0deg,red,blue)}",
		),
		(
			".a {\n\tbackground:linear-gradient(to top,red 0%,blue 100%);\n}\n",
			".a{background:linear-gradient(0deg,red,blue)}",
		),
		(
			"a{background:linear-gradient(to right,red,blue)}",
			"a{background:linear-gradient(90deg,red,blue)}",
		),
		(
			".a {\n\tbackground:linear-gradient(to right,red,blue);\n}\n",
			".a{background:linear-gradient(90deg,red,blue)}",
		),
		(
			"a{background:linear-gradient(to left top,red,blue)}",
			"a{background:linear-gradient(to left top,red,blue)}",
		),
		(
			".a {\n\tbackground:linear-gradient(to left top,red,blue);\n}\n",
			".a{background:linear-gradient(to left top,red,blue)}",
		),
		(
			"a{background:linear-gradient(180deg,#FFF 0%,#000 100%)}",
			"a{background:linear-gradient(180deg,#fff,#000)}",
		),
		(
			".a {\n\tbackground:linear-gradient(180deg,#FFF 0%,#000 100%);\n}\n",
			".a{background:linear-gradient(180deg,#fff,#000)}",
		),
		(
			"a{background:linear-gradient(red 50%,blue 40%)}",
			"a{background:linear-gradient(red 50%,blue 0)}",
		),
		(
			".a {\n\tbackground:linear-gradient(red 50%,blue 40%);\n}\n",
			".a{background:linear-gradient(red 50%,blue 0)}",
		),
		(
			"a{background:radial-gradient(circle at center,red 0%,blue 100%)}",
			"a{background:radial-gradient(circle at center,red,blue)}",
		),
		(
			".a {\n\tbackground:radial-gradient(circle at center,red 0%,blue 100%);\n}\n",
			".a{background:radial-gradient(circle at center,red,blue)}",
		),
		(
			"a{background:-webkit-linear-gradient(top,red 0%,blue 100%)}",
			"a{background:-webkit-linear-gradient(top,red,blue)}",
		),
		(
			".a {\n\tbackground:-webkit-linear-gradient(top,red 0%,blue 100%);\n}\n",
			".a{background:-webkit-linear-gradient(top,red,blue)}",
		),
		(
			"a{background:linear-gradient(to bottom,rgba(0,0,0,.5),transparent)}",
			"a{background:linear-gradient(180deg,rgba(0,0,0,.5),transparent)}",
		),
		(
			".a {\n\tbackground:linear-gradient(to bottom,rgba(0,0,0,.5),transparent);\n}\n",
			".a{background:linear-gradient(180deg,rgba(0,0,0,.5),transparent)}",
		),
		(
			"a{background:conic-gradient(red 0%,blue 100%)}",
			"a{background:conic-gradient(red,blue)}",
		),
		(
			".a {\n\tbackground:conic-gradient(red 0%,blue 100%);\n}\n",
			".a{background:conic-gradient(red,blue)}",
		),
	]);
}

#[test]
fn hacks_comments_and_custom_properties() {
	common::check_all(&[
		(
			"a{margin:0 auto!important;color:red ! important;color:red !IMPORTANT;color:red!important}",
			"a{margin:0 auto!important;color:red!important}",
		),
		(
			".a {\n\tmargin:0 auto!important;\n\tcolor:red ! important;\n\tcolor:red !IMPORTANT;\n\tcolor:red!important;\n}\n",
			".a{margin:0 auto!important;color:red!important}",
		),
		("a{color:red;;;color:blue}", "a{color:red;color:blue}"),
		(
			".a {\n\tcolor:red;\n\t;\n\t;\n\tcolor:blue;\n}\n",
			".a{color:red;color:blue}",
		),
		(
			"a{*zoom:1;_height:1px;color:red\\9;width:100px\\9;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#80000000', endColorstr='#80000000')}",
			"a{*zoom:1;_height:1px;color:red\\9;width:100px\\9;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=\"#80000000\",endColorstr=\"#80000000\")}",
		),
		(
			".a {\n\t*zoom:1;\n\t_height:1px;\n\tcolor:red\\9;\n\twidth:100px\\9;\n\tfilter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#80000000', endColorstr='#80000000');\n}\n",
			".a{*zoom:1;_height:1px;color:red\\9;width:100px\\9;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=\"#80000000\",endColorstr=\"#80000000\")}",
		),
		(
			"a{filter:alpha(opacity=50);-ms-filter:\"progid:DXImageTransform.Microsoft.Alpha(Opacity=50)\"}",
			"a{filter:alpha(opacity=50);-ms-filter:\"progid:DXImageTransform.Microsoft.Alpha(Opacity=50)\"}",
		),
		(
			".a {\n\tfilter:alpha(opacity=50);\n\t-ms-filter:\"progid:DXImageTransform.Microsoft.Alpha(Opacity=50)\";\n}\n",
			".a{filter:alpha(opacity=50);-ms-filter:\"progid:DXImageTransform.Microsoft.Alpha(Opacity=50)\"}",
		),
		(
			"a{width:expression(document.body.clientWidth > 800 ? \"800px\" : \"auto\")}",
			"a{width:expression(document.body.clientWidth > 800 ? \"800px\":\"auto\")}",
		),
		(
			".a {\n\twidth:expression(document.body.clientWidth > 800 ? \"800px\" : \"auto\");\n}\n",
			".a{width:expression(document.body.clientWidth > 800 ? \"800px\":\"auto\")}",
		),
		(
			"a{margin : 0   auto ;  padding:  1px   2px}",
			"a{margin:0 auto;padding:1px 2px}",
		),
		(
			".a {\n\tmargin : 0   auto ;\n\t  padding:  1px   2px;\n}\n",
			".a{margin:0 auto;padding:1px 2px}",
		),
		(
			"a{margin:0 /* c */ 1px;color:red/* c */}",
			"a{margin:0 1px;color:red}",
		),
		(
			".a {\n\tmargin:0 /* c */ 1px;\n\tcolor:red/* c */;\n}\n",
			".a{margin:0 1px;color:red}",
		),
		("a{margin:0/**/1px}", "a{margin:0 1px}"),
		(".a {\n\tmargin:0/**/1px;\n}\n", ".a{margin:0 1px}"),
		("a{/* c */color/* c */:/* c */red/* c */}", "a{color:red}"),
		(
			".a {\n\t/* c */color/* c */:/* c */red/* c */;\n}\n",
			".a{color:red}",
		),
		(
			"a{--a:  1px  ;--b:#FFF;--c: calc( 1px  +  2px );--d:{a:b}}",
			"a{--a:1px;--b:#fff;--c:3px;--d:{a:b}}",
		),
		(
			".a {\n\t--a:  1px  ;\n\t--b:#FFF;\n\t--c: calc( 1px  +  2px );\n\t--d:{a:b};\n}\n",
			".a{--a:1px;--b:#fff;--c:3px;--d:{a:b}}",
		),
		("a{--a:/* c */ 1px}", "a{--a:1px}"),
		(".a {\n\t--a:/* c */ 1px;\n}\n", ".a{--a:1px}"),
		(
			"a{--empty:;--space: ;--json:{\"a\": [1, 2]}}",
			"a{--empty:;--space:;--json:{\"a\": [1, 2]}}",
		),
		(
			".a {\n\t--empty:;\n\t--space: ;\n\t--json:{\"a\": [1, 2]};\n}\n",
			".a{--empty:;--space:;--json:{\"a\": [1, 2]}}",
		),
		(
			"a{foo:0px;colour:RED;-x-margin:0px;composes:a b from \"./x.css\"}",
			"a{foo:0;colour:red;-x-margin:0;composes:a b from \"./x.css\"}",
		),
		(
			".a {\n\tfoo:0px;\n\tcolour:RED;\n\t-x-margin:0px;\n\tcomposes:a b from \"./x.css\";\n}\n",
			".a{foo:0;colour:red;-x-margin:0;composes:a b from \"./x.css\"}",
		),
		(
			"a{-webkit-box-shadow:0 0 0px RED;*zoom:1.0;_height:0px}",
			"a{-webkit-box-shadow:0 0 0 red;*zoom:1;_height:0}",
		),
		(
			".a {\n\t-webkit-box-shadow:0 0 0px RED;\n\t*zoom:1.0;\n\t_height:0px;\n}\n",
			".a{-webkit-box-shadow:0 0 0 red;*zoom:1;_height:0}",
		),
		(
			"a{--x: 0.50px;--y: RED;--z: url( \"a.png\" )}",
			"a{--x:0.50px;--y:red;--z:url(a.png)}",
		),
		(
			".a {\n\t--x: 0.50px;\n\t--y: RED;\n\t--z: url( \"a.png\" );\n}\n",
			".a{--x:0.50px;--y:red;--z:url(a.png)}",
		),
		("a{width:calc(1px+2px)}", "a{width:3px}"),
		(".a {\n\twidth:calc(1px+2px);\n}\n", ".a{width:3px}"),
		(
			"a{width:calc(1px + var(--a));margin:calc(-1 * var(--x))}",
			"a{width:calc(1px + var(--a));margin:calc(var(--x)*-1)}",
		),
		(
			".a {\n\twidth:calc(1px + var(--a));\n\tmargin:calc(-1 * var(--x));\n}\n",
			".a{width:calc(1px + var(--a));margin:calc(var(--x)*-1)}",
		),
		("a{color:var(--a,#FFF)}", "a{color:var(--a,#fff)}"),
		(
			".a {\n\tcolor:var(--a,#FFF);\n}\n",
			".a{color:var(--a,#fff)}",
		),
		(
			"a{background:url(a.png)   no-repeat  ,  url(b.png)   repeat-x}",
			"a{background:url(a.png) no-repeat,url(b.png) repeat-x}",
		),
		(
			".a {\n\tbackground:url(a.png)   no-repeat  ,  url(b.png)   repeat-x;\n}\n",
			".a{background:url(a.png) no-repeat,url(b.png) repeat-x}",
		),
		(
			"a{src:url(\"a.woff2\") format(\"woff2\"),url('a.woff') format('woff')}",
			"a{src:url(a.woff2) format(\"woff2\"),url(a.woff) format(\"woff\")}",
		),
		(
			".a {\n\tsrc:url(\"a.woff2\") format(\"woff2\"),url('a.woff') format('woff');\n}\n",
			".a{src:url(a.woff2) format(\"woff2\"),url(a.woff) format(\"woff\")}",
		),
		(
			"a{will-change:transform , opacity}",
			"a{will-change:transform,opacity}",
		),
		(
			".a {\n\twill-change:transform , opacity;\n}\n",
			".a{will-change:transform,opacity}",
		),
		(
			"a{transition:opacity .3s,transform .3s}",
			"a{transition:opacity .3s,transform .3s}",
		),
		(
			".a {\n\ttransition:opacity .3s,transform .3s;\n}\n",
			".a{transition:opacity .3s,transform .3s}",
		),
		(
			"a{font-feature-settings:\"liga\" 1 , \"kern\" 1}",
			"a{font-feature-settings:\"liga\" 1,\"kern\" 1}",
		),
		(
			".a {\n\tfont-feature-settings:\"liga\" 1 , \"kern\" 1;\n}\n",
			".a{font-feature-settings:\"liga\" 1,\"kern\" 1}",
		),
		(
			"a{mask:url(a.svg#b) center / contain no-repeat}",
			"a{mask:url(a.svg#b) center/contain no-repeat}",
		),
		(
			".a {\n\tmask:url(a.svg#b) center / contain no-repeat;\n}\n",
			".a{mask:url(a.svg#b) center/contain no-repeat}",
		),
	]);
}

#[test]
fn at_rules() {
	common::check_all(&[
		(
			"@import url(\"a.css\");\n@import \"b.css\" screen;\n@import url(c.css) screen and (min-width:100px);\na{b:c}\n",
			"@import url(\"a.css\");@import \"b.css\" screen;@import url(c.css) screen and (min-width:100px);a{b:c}",
		),
		("@charset \"utf-8\";a{color:red}", "a{color:red}"),
		(
			"@charset \"utf-8\";a{content:\"é\"}",
			"@charset \"utf-8\";a{content:\"é\"}",
		),
		(
			"a{content:\"é\"}@charset \"utf-8\";",
			"@charset \"utf-8\";a{content:\"é\"}",
		),
		("@media all{a{color:red}}", "@media{a{color:red}}"),
		(
			"@media all and (min-width:100px){a{color:red}}",
			"@media (min-width:100px){a{color:red}}",
		),
		(
			"@media screen and (min-width : 100px) , print{a{color:red}}",
			"@media print,screen and (min-width:100px){a{color:red}}",
		),
		(
			"@media (min-width:100px) and (max-width:200px),(min-width:300px){a{color:red}}",
			"@media (min-width:100px) and (max-width:200px),(min-width:300px){a{color:red}}",
		),
		(
			"@media(min-width:100px){a{color:red}}",
			"@media(min-width:100px){a{color:red}}",
		),
		(
			"@media   screen   and   (min-width:100px){a{color:red}}",
			"@media screen and (min-width:100px){a{color:red}}",
		),
		(
			"@media (min-aspect-ratio: 16/9){a{color:red}}",
			"@media (min-aspect-ratio:16/9){a{color:red}}",
		),
		(
			"@media (min-aspect-ratio: 32/18){a{color:red}}",
			"@media (min-aspect-ratio:16/9){a{color:red}}",
		),
		(
			"@media (width >= 600px) and (width <= 900px){a{color:red}}",
			"@media (width >= 600px) and (width <= 900px){a{color:red}}",
		),
		(
			"@media (400px <= width <= 700px){a{color:red}}",
			"@media (400px <= width <= 700px){a{color:red}}",
		),
		(
			"@media not all and (monochrome){a{color:red}}",
			"@media not all and (monochrome){a{color:red}}",
		),
		(
			"@media only screen and (-webkit-min-device-pixel-ratio:1.5),only screen and (min-resolution:144dpi){a{color:red}}",
			"@media only screen and (-webkit-min-device-pixel-ratio:1.5),only screen and (min-resolution:144dpi){a{color:red}}",
		),
		(
			"@supports (display:grid) and (not (display:inline-grid)){a{color:red}}",
			"@supports (display:grid) and (not (display:inline-grid)){a{color:red}}",
		),
		(
			"@supports not (display : grid){a{color:red}}",
			"@supports not (display:grid){a{color:red}}",
		),
		(
			"@supports (--css: variables){a{color:red}}",
			"@supports (--css:variables){a{color:red}}",
		),
		(
			"@supports selector(:has(a)){a{color:red}}",
			"@supports selector(:has(a)){a{color:red}}",
		),
		(
			"@container (min-width: 400px){a{color:red}}",
			"@container (min-width: 400px){a{color:red}}",
		),
		(
			"@container sidebar (min-width:400px) and (max-width:  500px){a{color:red}}",
			"@container sidebar (min-width:400px) and (max-width:  500px){a{color:red}}",
		),
		(
			"@layer a,b;\n@layer a{a{color:red}}\n",
			"@layer a,b;@layer a{a{color:red}}",
		),
		("@layer a , b ;a{b:c}", "@layer a , b;a{b:c}"),
		(
			"@layer a{}\n@layer a{a{b:c}}\n",
			"@layer a{}@layer a{a{b:c}}",
		),
		("@layer a{@layer b{c{d:e}}}", "@layer a{@layer b{c{d:e}}}"),
		(
			"@font-face{font-family:\"A\";src:url(\"a.woff2\") format(\"woff2\"),url('a.woff') format('woff');font-display:swap;unicode-range:U+0000-00FF,U+0131}",
			"@font-face{font-family:A;src:url(a.woff2) format(\"woff2\"),url(a.woff) format(\"woff\");font-display:swap;unicode-range:u+00??,u+0131}",
		),
		(
			"@keyframes x{from{a:b}to{a:c}}",
			"@keyframes x{0%{a:b}to{a:c}}",
		),
		(
			"@keyframes x{0%{a:b}100%{a:c}}",
			"@keyframes x{0%{a:b}to{a:c}}",
		),
		(
			"@keyframes x{from{a:b}to{a:c}}@keyframes x{from{a:d}to{a:e}}",
			"@keyframes x{0%{a:d}to{a:e}}",
		),
		(
			"@-webkit-keyframes x{from{a:b}}@keyframes x{from{a:b}}",
			"@-webkit-keyframes x{0%{a:b}}@keyframes x{0%{a:b}}",
		),
		("@keyframes x{50%,0%{a:b}}", "@keyframes x{0%,50%{a:b}}"),
		(
			"@keyframes x{0%{width:0%;stroke-dasharray:0%}to{width:100%}}",
			"@keyframes x{0%{width:0;stroke-dasharray:0%}to{width:100%}}",
		),
		("@page :first{margin:0px}", "@page :first{margin:0}"),
		(
			"@page{@top-left{content:\"a\"}}",
			"@page{@top-left{content:\"a\"}}",
		),
		(
			"@property --x{syntax:'<length>';inherits:false;initial-value:0px}",
			"@property --x{syntax:\"<length>\";inherits:false;initial-value:0}",
		),
		(
			"@property --p{syntax:'<percentage>';inherits:false;initial-value:0%}",
			"@property --p{syntax:\"<percentage>\";inherits:false;initial-value:0%}",
		),
		(
			"@namespace svg url(http://www.w3.org/2000/svg);\n@namespace url(http://www.w3.org/1999/xhtml);\n",
			"@namespace svg \"http://www.w3.org/2000/svg\";@namespace \"http://www.w3.org/1999/xhtml\";",
		),
		(
			"@counter-style x{system:cyclic;symbols:\"a\"}",
			"@counter-style x{system:cyclic;symbols:\"a\"}",
		),
		(
			"@font-feature-values Font One{@styleset{nice-style:12}}",
			"@font-feature-values Font One{@styleset{nice-style:12}}",
		),
		(
			"@unknown foo  bar {a   :  b  ;  c:d}",
			"@unknown foo  bar{a:b;c:d}",
		),
		(
			"@media print{@media (min-width:1px){a{b:c}}}",
			"@media print{@media (min-width:1px){a{b:c}}}",
		),
	]);
}

#[test]
fn duplicates_and_empty_rules() {
	common::check_all(&[
		("a{color:red}a{color:red}", "a{color:red}"),
		(
			"a{color:red;margin:0}b{x:y}a{color:red}",
			"a{margin:0}b{x:y}a{color:red}",
		),
		(
			"a{color:red}b{color:blue}a{color:red}",
			"b{color:blue}a{color:red}",
		),
		("@media a{a{b:c}}@media a{a{b:c}}", "@media a{a{b:c}}"),
		("a{b:c}@media a{a{b:c}}", "a{b:c}@media a{a{b:c}}"),
		("a,b{x:y}b,a{x:y}a,a{x:y}", "a,b{x:y}"),
		(
			"a{}\na{;}\n@media screen{}\n@media screen{a{}}\na{color:red}b{}\n@font-face{}\n",
			"a{color:red}",
		),
	]);
}

#[test]
fn selectors() {
	common::check_all(&[
		("a b > c + d ~ e{x:1}", "a b>c+d~e{x:1}"),
		("a>b+c~d{x:1}", "a>b+c~d{x:1}"),
		("a   >   b{x:1}\na ,  b{x:2}\n", "a>b{x:1}a,b{x:2}"),
		(
			"a:not(.b,.c):is(.d, .e){x:1}",
			"a:not(.b,.c):is(.d,.e){x:1}",
		),
		("a:not(.b,.b){x:1}", "a:not(.b){x:1}"),
		(
			"a:nth-child(1){x:1}a:nth-child(2n+1){x:2}a:nth-child(even){x:3}a:nth-child( 2n + 1 ){x:4}",
			"a:first-child{x:1}a:nth-child(odd){x:2}a:nth-child(2n){x:3}a:nth-child(odd){x:4}",
		),
		(
			"a:nth-child(2n+1 of .b){x:1}a:nth-last-child(1){x:2}a:nth-of-type(1){x:3}a:nth-child(n+2){x:4}",
			"a:nth-child(2n+1 of .b){x:1}a:last-child{x:2}a:first-of-type{x:3}a:nth-child(n+2){x:4}",
		),
		(
			"a::before{x:1}a::after,a::first-line{x:2}a::selection{x:3}a:BEFORE{x:4}",
			"a:before{x:1}a:after,a:first-line{x:2}a::selection{x:3}a:BEFORE{x:4}",
		),
		(
			"*.a{x:1}*{x:2}* a{x:3}a *{x:4}*:hover{x:5}a>*{x:6}*|*{x:7}",
			".a{x:1}*{x:2}* a{x:3}a *{x:4}:hover{x:5}a>*{x:6}*|*{x:7}",
		),
		(
			"a[href=\"x\"]{x:1}a[href='x']{x:2}a[ href = \"x\" ]{x:3}a[href=\"x y\"]{x:4}a[href=\"1x\"]{x:5}a[href=\"\"]{x:6}",
			"a[href=x]{x:1;x:2;x:3}a[href=\"x y\"]{x:4}a[href=\"1x\"]{x:5}a[href=\"\"]{x:6}",
		),
		(
			"a[href=\"x\" i]{x:1}a[href=x i]{x:2}a[href^=\"http\"]{x:3}a[data-a=\"a-b\"]{x:4}a[data-a=\"a_b\"]{x:5}",
			"a[href=x i]{x:1}a[href=x i]{x:2}a[href^=http]{x:3}a[data-a=a-b]{x:4}a[data-a=a_b]{x:5}",
		),
		(
			"a[href~=\"x\"]{x:1}a[href|=x]{x:2}a[lang|=\"en\"]{x:3}",
			"a[href~=x]{x:1}a[href|=x]{x:2}a[lang|=en]{x:3}",
		),
		(
			".a\\:b{x:1}.a\\31 b{x:2}.\\31 0{x:3}",
			".a\\:b{x:1}.a\\31 b{x:2}.\\31 0{x:3}",
		),
		(
			"a  .b{x:1}a:hover,a:focus{x:2}html>/**/body{x:3}",
			"a .b{x:1}a:focus,a:hover{x:2}html>body{x:3}",
		),
		("a\n\tb{x:1}", "a\n\tb{x:1}"),
	]);
}

#[test]
fn nesting_and_comments() {
	common::check_all(&[
		(
			".a{&:hover{x:1}}.a{& .b{x:2}}.a{&.b{x:3}}.a{.b &{x:4}}",
			".a{&:hover{x:1}}.a{& .b{x:2}}.a{&.b{x:3}}.a{.b &{x:4}}",
		),
		(".a{> .b{x:1}}.a{+ .b{x:2}}", ".a{>.b{x:1}}.a{+.b{x:2}}"),
		(
			".a{color:red;&:hover{color:blue}}",
			".a{color:red;&:hover{color:blue}}",
		),
		(
			".a{color:red;@media (min-width:1px){color:blue}}",
			".a{color:red;@media (min-width:1px){color:blue}}",
		),
		(
			".a{@media (min-width:1px){color:blue}}",
			".a{@media (min-width:1px){color:blue}}",
		),
		(".a{& > .b{x:1} .c{x:2}}", ".a{&>.b{x:1}.c{x:2}}"),
		(
			":root{--a:  1px  ;--b:#FFF;--c: calc( 1px  +  2px );--d:{a:b}}",
			":root{--a:1px;--b:#fff;--c:3px;--d:{a:b}}",
		),
		("/*! keep */a{x:1}", "/*! keep */a{x:1}"),
		("/* drop */a{x:1}/*! keep2 */", "a{x:1}/*! keep2 */"),
		("a{x:y;/*! keep */}", "a{x:y/*! keep */}"),
		("a{}/*! keep */", "/*! keep */"),
		(
			"@media screen{/*! keep */a{x:1}}",
			"@media screen{/*! keep */a{x:1}}",
		),
	]);
}

#[test]
fn error_recovery() {
	common::check_all(&[
		("a{color:red", "__ERROR__"),
		("a{color:red;", "__ERROR__"),
		("a{color:\"red", "__ERROR__"),
		("a{color:red}}", "__ERROR__"),
		("a{b:c}}d{e:f}", "__ERROR__"),
		("a{b:c};d{e:f}", "a{b:c};d{e:f}"),
		("a{b:c}\n;\nd{e:f}", "a{b:c}\n;d{e:f}"),
		("a{b", "__ERROR__"),
		("a{b:}", ""),
		("a{:c}", ""),
		("a{b:c;d}", "__ERROR__"),
		("a{b:c;;d:e}", "a{b:c;d:e}"),
		("a{b:c d:e}", "__ERROR__"),
		("/* unterminated", "__ERROR__"),
		("a{b:c}/* unterminated", "__ERROR__"),
		("@media screen{a{b:c}", "__ERROR__"),
		("@media screen", "@media screen"),
		("@import \"a\"", "@import \"a\""),
		("@import \"a\";", "@import \"a\";"),
		("a{b:url(x", "__ERROR__"),
		("a{b:url(\"x}", "__ERROR__"),
		("a{b:(c}d:e}", "__ERROR__"),
		("<!-- a{b:c} -->", "__ERROR__"),
		("a{b:c}<!--d{e:f}-->", "__ERROR__"),
		(
			"a{b:c !important !important}",
			"a{b:c !important!important}",
		),
		("a{b:c!ie}", "a{b:c!ie}"),
		("a{b:c\\}", "__ERROR__"),
		("a{b:c\\;d:e}", "__ERROR__"),
		("a{b:\\}}", "a{b:\\}}"),
		("a { b : c ; } ; b { c : d }", "a{b:c} ;b{c:d}"),
		("}a{b:c}", "__ERROR__"),
		("{a:b}", ""),
		("a{{b:c}}", ""),
		("a{b{c:d}e:f}", "a{b{c:d}e:f}"),
		("a b{c:d}\ne{f:g}", "a b{c:d}e{f:g}"),
		(
			"@font-face{font-family:a;src:url(a)}@font-face{font-family:a;src:url(a)}",
			"@font-face{font-family:a;src:url(a)}",
		),
		("", ""),
		("   \n  ", ""),
		("/**/", ""),
		("\u{feff}a{b:c}", "\u{feff}a{b:c}"),
		("a{b:c}\r\nd{e:f}\r\n", "a{b:c}d{e:f}"),
		("a{b:c\u{a0}d}", "a{b:c\u{a0}d}"),
		("a{content:\"éあ\"}b{c:d}", "a{content:\"éあ\"}b{c:d}"),
		(".あ{b:c}", ".あ{b:c}"),
		("a{b:c}\u{0}d{e:f}", "a{b:c}\u{0}d{e:f}"),
	]);
}
