//! The bytes of a page in the character encoding it is delivered in.
//!
//! A site that is still served as Shift_JIS (an older Japanese site, say) writes its pages in UTF-8 and
//! has them converted when they are written. This does what d-zero/builder did with
//! `charset: { encoding: 'shift_jis' }`:
//!
//! - `<meta charset="utf-8">` becomes `<meta charset="shift_jis">`;
//! - the text is encoded as Windows Shift_JIS (CP932, what `iconv-lite` calls `CP932`);
//! - a character that the encoding cannot hold is written as a character reference, its
//!   name (`&copy;`) when it has one and its number (`&#12316;`) when not, so that nothing is
//!   lost and the browser shows the same text. Inside `<script>` and `<style>` a reference
//!   would be read as text, so there the character becomes `?` (what `iconv-lite` writes).
//!
//! The table of two-byte characters is generated by `scripts/gen-cp932-table.mjs`.

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::cp932_table::{DOUBLE, TRAILS};
use crate::entities::name_of;

/// The encoding a page is written in.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Encoding {
	/// UTF-8, as it is.
	#[default]
	Utf8,
	/// Windows Shift_JIS (CP932).
	ShiftJis,
}

/// What an encoded character is, by code point.
fn reverse() -> &'static HashMap<u16, u16> {
	static TABLE: OnceLock<HashMap<u16, u16>> = OnceLock::new();
	TABLE.get_or_init(|| {
		let mut map = HashMap::with_capacity(DOUBLE.len());
		for (pointer, &cp) in DOUBLE.iter().enumerate() {
			// The pointers of the NEC-selected IBM extensions are left to the IBM ones
			// (the WHATWG encoder does the same, and so does Microsoft).
			if cp == 0 || (8272..=8835).contains(&pointer) {
				continue;
			}
			let lead = pointer / TRAILS;
			let trail = pointer % TRAILS;
			let lead_byte = if lead < 31 { 0x81 + lead } else { 0xC1 + lead };
			let trail_byte = if trail < 63 {
				0x40 + trail
			} else {
				0x41 + trail
			};
			map.entry(cp)
				.or_insert(((lead_byte << 8) | trail_byte) as u16);
		}
		map
	})
}

/// The bytes of one character, or `None` when Shift_JIS has none for it.
fn shift_jis_of(c: char) -> Option<([u8; 2], usize)> {
	let cp = c as u32;
	match cp {
		0..=0x80 => Some(([cp as u8, 0], 1)),
		// The yen sign and the overline are the backslash and the tilde of JIS X 0201.
		0xA5 => Some(([0x5C, 0], 1)),
		0x203E => Some(([0x7E, 0], 1)),
		// Half-width katakana.
		0xFF61..=0xFF9F => Some((([(cp - 0xFF61 + 0xA1) as u8, 0]), 1)),
		// The private use area is not a part of CP932 for `iconv-lite`.
		0xE000..=0xF8FF => None,
		0x81..=0xFFFF => reverse()
			.get(&(cp as u16))
			.map(|&b| (([(b >> 8) as u8, (b & 0xFF) as u8]), 2)),
		_ => None,
	}
}

/// Rewrites `<meta charset="utf-8">` (and `utf8`, any case, with or without the closing `/`) to
/// name `charset`.
fn rewrite_meta_charset(html: &str, charset: &str) -> String {
	let lower = html.to_ascii_lowercase();
	let bytes = lower.as_bytes();
	let mut out = String::with_capacity(html.len());
	let mut last = 0;
	let mut from = 0;
	while let Some(found) = lower[from..].find("<meta") {
		let start = from + found;
		from = start + 5;
		let mut i = start + 5;
		let mut spaces = 0;
		while i < bytes.len() && bytes[i].is_ascii_whitespace() {
			i += 1;
			spaces += 1;
		}
		if spaces == 0 || !lower[i..].starts_with("charset=\"") {
			continue;
		}
		i += 9;
		let value_end = match lower[i..].find('"') {
			Some(n) => i + n,
			None => continue,
		};
		if !matches!(&lower[i..value_end], "utf-8" | "utf8") {
			continue;
		}
		let mut j = value_end + 1;
		while j < bytes.len() && bytes[j].is_ascii_whitespace() {
			j += 1;
		}
		if bytes.get(j) == Some(&b'/') {
			j += 1;
		}
		if bytes.get(j) != Some(&b'>') {
			continue;
		}
		out.push_str(&html[last..start]);
		out.push_str(&format!("<meta charset=\"{charset}\">"));
		last = j + 1;
		from = last;
	}
	out.push_str(&html[last..]);
	out
}

/// The ranges of `<script>` and `<style>` text, where a character reference is not one.
fn raw_text_ranges(html: &str) -> Vec<(usize, usize)> {
	let lower = html.to_ascii_lowercase();
	let mut ranges = Vec::new();
	for tag in ["script", "style"] {
		let open = format!("<{tag}");
		let close = format!("</{tag}");
		let mut from = 0;
		while let Some(found) = lower[from..].find(&open) {
			let start = from + found;
			let after = start + open.len();
			// `<scripts>` is not a script.
			if !matches!(
				lower.as_bytes().get(after),
				Some(b'>' | b' ' | b'\t' | b'\n' | b'\r' | b'/')
			) {
				from = after;
				continue;
			}
			let Some(gt) = lower[after..].find('>') else {
				break;
			};
			let text_start = after + gt + 1;
			let text_end = lower[text_start..]
				.find(&close)
				.map_or(lower.len(), |n| text_start + n);
			ranges.push((text_start, text_end));
			from = text_end;
		}
	}
	ranges.sort_unstable();
	ranges
}

/// Encodes `html` as the bytes to write.
///
/// # Example
///
/// ```
/// use kd_html::encode::{encode, Encoding};
///
/// assert_eq!(encode("日本", Encoding::Utf8), "日本".as_bytes());
/// // Shift_JIS: two bytes for each of the two characters.
/// assert_eq!(encode("日本", Encoding::ShiftJis), [0x93, 0xFA, 0x96, 0x7B]);
/// // What it cannot hold becomes a character reference.
/// assert_eq!(encode("© 〜", Encoding::ShiftJis), b"&copy; &#12316;");
/// ```
#[must_use]
pub fn encode(html: &str, encoding: Encoding) -> Vec<u8> {
	match encoding {
		Encoding::Utf8 => html.as_bytes().to_vec(),
		Encoding::ShiftJis => to_shift_jis(html),
	}
}

fn to_shift_jis(html: &str) -> Vec<u8> {
	let rewritten;
	let html = if html.contains("<meta") || html.contains("<META") {
		rewritten = rewrite_meta_charset(html, "shift_jis");
		rewritten.as_str()
	} else {
		html
	};
	let raw = if html.is_ascii() {
		Vec::new()
	} else {
		raw_text_ranges(html)
	};
	let mut out = Vec::with_capacity(html.len());
	let mut next_raw = 0;
	let mut buf = [0u8; 4];
	for (at, c) in html.char_indices() {
		if c.is_ascii() {
			out.push(c as u8);
			continue;
		}
		if let Some((bytes, n)) = shift_jis_of(c) {
			out.extend_from_slice(&bytes[..n]);
			continue;
		}
		while next_raw < raw.len() && raw[next_raw].1 <= at {
			next_raw += 1;
		}
		if next_raw < raw.len() && raw[next_raw].0 <= at {
			out.push(b'?');
			continue;
		}
		match name_of(c.encode_utf8(&mut buf)) {
			Some(name) => {
				out.push(b'&');
				out.extend_from_slice(name.as_bytes());
				out.push(b';');
			}
			None => out.extend_from_slice(format!("&#{};", c as u32).as_bytes()),
		}
	}
	out
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn ascii_and_common_japanese_are_encoded_like_cp932() {
		assert_eq!(encode("abc", Encoding::ShiftJis), b"abc");
		assert_eq!(
			encode("日本語", Encoding::ShiftJis),
			[0x93, 0xFA, 0x96, 0x7B, 0x8C, 0xEA]
		);
		// Half-width katakana is one byte, the full-width form two.
		assert_eq!(encode("ｱア", Encoding::ShiftJis), [0xB1, 0x83, 0x41]);
	}

	#[test]
	fn windows_extensions_and_the_yen_sign_are_encoded() {
		// NEC row 13 and IBM extensions: the circled digit, the roman numeral, a kanji of IBM.
		assert_eq!(encode("①", Encoding::ShiftJis), [0x87, 0x40]);
		assert_eq!(encode("Ⅲ", Encoding::ShiftJis), [0x87, 0x56]);
		assert_eq!(
			encode("㈱№∵－", Encoding::ShiftJis),
			[0x87, 0x8A, 0x87, 0x82, 0x81, 0xE6, 0x81, 0x7C]
		);
		assert_eq!(encode("髙", Encoding::ShiftJis), [0xFB, 0xFC]);
		assert_eq!(encode("¥", Encoding::ShiftJis), [0x5C]);
	}

	#[test]
	fn what_the_encoding_cannot_hold_is_a_character_reference() {
		assert_eq!(encode("©", Encoding::ShiftJis), b"&copy;");
		// The wave dash (U+301C) is not the fullwidth tilde (U+FF5E) of CP932.
		assert_eq!(encode("〜", Encoding::ShiftJis), b"&#12316;");
		assert_eq!(encode("⚠", Encoding::ShiftJis), b"&#9888;");
	}

	#[test]
	fn a_script_or_style_gets_a_question_mark_because_a_reference_would_be_text() {
		let html =
			"<p>©</p><script>var a = '©';</script><style>a::after{content:'©'}</style><p>〜</p>";
		assert_eq!(
			String::from_utf8(encode(html, Encoding::ShiftJis)).unwrap(),
			"<p>&copy;</p><script>var a = '?';</script><style>a::after{content:'?'}</style><p>&#12316;</p>"
		);
	}

	#[test]
	fn the_meta_charset_names_shift_jis() {
		for meta in [
			"<meta charset=\"utf-8\" />",
			"<meta charset=\"UTF-8\">",
			"<META  charset=\"utf8\"/>",
		] {
			assert_eq!(
				encode(&format!("<head>{meta}</head>"), Encoding::ShiftJis),
				b"<head><meta charset=\"shift_jis\"></head>"
			);
		}
		// Another charset, or another attribute, is left as it is.
		assert_eq!(
			encode(
				"<meta charset=\"euc-jp\"><meta name=\"charset\" content=\"utf-8\">",
				Encoding::ShiftJis
			),
			b"<meta charset=\"euc-jp\"><meta name=\"charset\" content=\"utf-8\">"
		);
	}

	#[test]
	fn the_private_use_area_is_not_mapped() {
		assert_eq!(encode("\u{E000}", Encoding::ShiftJis), b"&#57344;");
	}

	#[test]
	fn utf8_is_the_text_as_it_is() {
		assert_eq!(encode("日本©", Encoding::Utf8), "日本©".as_bytes());
	}
}
