//! @generated by scripts/generate-jsx-tables.mjs — do not edit by hand.
//! Source: react-dom 19.2.8 (cjs/react-dom-server-legacy.node.production.js), read as
//! text; nothing is probed by rendering.
//!
//! The attribute table React DOM applies to host element props, as far as it
//! differs from "write the name as is".

/// Written as `name="escaped value"`; function, symbol and boolean values are dropped.
pub const STRING: u8 = 0;
/// Truthy value writes `name=""`, falsy / function / symbol writes nothing.
pub const BOOLEAN: u8 = 1;
/// `true` writes `name=""`, `false` writes nothing, anything else is a string.
pub const OVERLOADED_BOOLEAN: u8 = 2;
/// Dropped when the value is not a number (`isNaN`), otherwise a string.
pub const NUMERIC: u8 = 3;
/// Like [`NUMERIC`] and additionally dropped below 1.
pub const POSITIVE_NUMERIC: u8 = 4;
/// A string even for booleans (`contentEditable="true"`).
pub const BOOLEANISH_STRING: u8 = 5;
/// Never written (`defaultValue`, `ref`, `suppressHydrationWarning`, ...).
pub const RESERVED: u8 = 6;
/// `src` / `href`: sanitised (`javascript:` URLs are rewritten), an empty string, function, symbol
/// and boolean are dropped. (React has no such "kind"; it is a separate branch of its switch.)
pub const URL_ATTR: u8 = 7;
/// `action`, `formAction`, `xlinkHref`: like [`URL_ATTR`] but an empty string is kept.
pub const URL_ATTR_KEEP_EMPTY: u8 = 8;
/// `style`: an object of CSS declarations (see the runtime), a string throws.
pub const STYLE: u8 = 9;

/// `(React prop name, HTML attribute name as React writes it, kind)`, sorted by prop name in byte order.
///
/// Props React writes unchanged as plain strings (`id`, `title`, `alt`, `lang`, ...) are not in the
/// table: [`lookup`] returning `None` means "write the name as is, kind [`STRING`]". Further rules
/// that are not table entries:
///
/// - `aria-*` and `data-*` props are written as is; unlike other [`STRING`] props their boolean
///   values are written (`aria-hidden="true"`), i.e. they behave like [`BOOLEANISH_STRING`].
/// - A name starting with `on` (any case, longer than two characters) that is not in the table is an
///   event handler and is dropped, as is a name that is not a valid attribute name.
/// - `key`, `children` and `dangerouslySetInnerHTML` are consumed by the element, not written.
/// - Custom elements (a `-` in the tag name) skip this table entirely and write names as is.
pub static PROPS: [(&str, &str, u8); 142] = [
	("accentHeight", "accent-height", STRING),
	("acceptCharset", "accept-charset", STRING),
	("action", "action", URL_ATTR_KEEP_EMPTY),
	("alignmentBaseline", "alignment-baseline", STRING),
	("allowFullScreen", "allowFullScreen", BOOLEAN),
	("arabicForm", "arabic-form", STRING),
	("async", "async", BOOLEAN),
	("autoFocus", "autofocus", BOOLEAN),
	("autoPlay", "autoPlay", BOOLEAN),
	("autoReverse", "autoReverse", BOOLEANISH_STRING),
	("baselineShift", "baseline-shift", STRING),
	("capHeight", "cap-height", STRING),
	("capture", "capture", OVERLOADED_BOOLEAN),
	("className", "class", STRING),
	("clipPath", "clip-path", STRING),
	("clipRule", "clip-rule", STRING),
	("colorInterpolation", "color-interpolation", STRING),
	(
		"colorInterpolationFilters",
		"color-interpolation-filters",
		STRING,
	),
	("colorProfile", "color-profile", STRING),
	("colorRendering", "color-rendering", STRING),
	("cols", "cols", POSITIVE_NUMERIC),
	("contentEditable", "contentEditable", BOOLEANISH_STRING),
	("controls", "controls", BOOLEAN),
	("crossOrigin", "crossorigin", STRING),
	("default", "default", BOOLEAN),
	("defaultChecked", "defaultChecked", RESERVED),
	("defaultValue", "defaultValue", RESERVED),
	("defer", "defer", BOOLEAN),
	(
		"disablePictureInPicture",
		"disablePictureInPicture",
		BOOLEAN,
	),
	("disableRemotePlayback", "disableRemotePlayback", BOOLEAN),
	("disabled", "disabled", BOOLEAN),
	("dominantBaseline", "dominant-baseline", STRING),
	("download", "download", OVERLOADED_BOOLEAN),
	("draggable", "draggable", BOOLEANISH_STRING),
	("enableBackground", "enable-background", STRING),
	(
		"externalResourcesRequired",
		"externalResourcesRequired",
		BOOLEANISH_STRING,
	),
	("fillOpacity", "fill-opacity", STRING),
	("fillRule", "fill-rule", STRING),
	("floodColor", "flood-color", STRING),
	("floodOpacity", "flood-opacity", STRING),
	("focusable", "focusable", BOOLEANISH_STRING),
	("fontFamily", "font-family", STRING),
	("fontSize", "font-size", STRING),
	("fontSizeAdjust", "font-size-adjust", STRING),
	("fontStretch", "font-stretch", STRING),
	("fontStyle", "font-style", STRING),
	("fontVariant", "font-variant", STRING),
	("fontWeight", "font-weight", STRING),
	("formAction", "formAction", URL_ATTR_KEEP_EMPTY),
	("formNoValidate", "formNoValidate", BOOLEAN),
	("glyphName", "glyph-name", STRING),
	(
		"glyphOrientationHorizontal",
		"glyph-orientation-horizontal",
		STRING,
	),
	(
		"glyphOrientationVertical",
		"glyph-orientation-vertical",
		STRING,
	),
	("hidden", "hidden", BOOLEAN),
	("horizAdvX", "horiz-adv-x", STRING),
	("horizOriginX", "horiz-origin-x", STRING),
	("href", "href", URL_ATTR),
	("htmlFor", "for", STRING),
	("httpEquiv", "http-equiv", STRING),
	("imageRendering", "image-rendering", STRING),
	("inert", "inert", BOOLEAN),
	("innerHTML", "innerHTML", RESERVED),
	("itemScope", "itemScope", BOOLEAN),
	("letterSpacing", "letter-spacing", STRING),
	("lightingColor", "lighting-color", STRING),
	("loop", "loop", BOOLEAN),
	("markerEnd", "marker-end", STRING),
	("markerMid", "marker-mid", STRING),
	("markerStart", "marker-start", STRING),
	("multiple", "multiple", BOOLEAN),
	("muted", "muted", BOOLEAN),
	("noModule", "noModule", BOOLEAN),
	("noValidate", "noValidate", BOOLEAN),
	("open", "open", BOOLEAN),
	("overlinePosition", "overline-position", STRING),
	("overlineThickness", "overline-thickness", STRING),
	("paintOrder", "paint-order", STRING),
	("playsInline", "playsInline", BOOLEAN),
	("pointerEvents", "pointer-events", STRING),
	("preserveAlpha", "preserveAlpha", BOOLEANISH_STRING),
	("readOnly", "readOnly", BOOLEAN),
	("ref", "ref", RESERVED),
	("renderingIntent", "rendering-intent", STRING),
	("required", "required", BOOLEAN),
	("reversed", "reversed", BOOLEAN),
	("rowSpan", "rowSpan", NUMERIC),
	("rows", "rows", POSITIVE_NUMERIC),
	("scoped", "scoped", BOOLEAN),
	("seamless", "seamless", BOOLEAN),
	("shapeRendering", "shape-rendering", STRING),
	("size", "size", POSITIVE_NUMERIC),
	("span", "span", POSITIVE_NUMERIC),
	("spellCheck", "spellCheck", BOOLEANISH_STRING),
	("src", "src", URL_ATTR),
	("start", "start", NUMERIC),
	("stopColor", "stop-color", STRING),
	("stopOpacity", "stop-opacity", STRING),
	("strikethroughPosition", "strikethrough-position", STRING),
	("strikethroughThickness", "strikethrough-thickness", STRING),
	("strokeDasharray", "stroke-dasharray", STRING),
	("strokeDashoffset", "stroke-dashoffset", STRING),
	("strokeLinecap", "stroke-linecap", STRING),
	("strokeLinejoin", "stroke-linejoin", STRING),
	("strokeMiterlimit", "stroke-miterlimit", STRING),
	("strokeOpacity", "stroke-opacity", STRING),
	("strokeWidth", "stroke-width", STRING),
	("style", "style", STYLE),
	(
		"suppressContentEditableWarning",
		"suppressContentEditableWarning",
		RESERVED,
	),
	(
		"suppressHydrationWarning",
		"suppressHydrationWarning",
		RESERVED,
	),
	("tabIndex", "tabindex", STRING),
	("textAnchor", "text-anchor", STRING),
	("textDecoration", "text-decoration", STRING),
	("textRendering", "text-rendering", STRING),
	("transformOrigin", "transform-origin", STRING),
	("underlinePosition", "underline-position", STRING),
	("underlineThickness", "underline-thickness", STRING),
	("unicodeBidi", "unicode-bidi", STRING),
	("unicodeRange", "unicode-range", STRING),
	("unitsPerEm", "units-per-em", STRING),
	("vAlphabetic", "v-alphabetic", STRING),
	("vHanging", "v-hanging", STRING),
	("vIdeographic", "v-ideographic", STRING),
	("vMathematical", "v-mathematical", STRING),
	("value", "value", BOOLEANISH_STRING),
	("vectorEffect", "vector-effect", STRING),
	("vertAdvY", "vert-adv-y", STRING),
	("vertOriginX", "vert-origin-x", STRING),
	("vertOriginY", "vert-origin-y", STRING),
	("wordSpacing", "word-spacing", STRING),
	("writingMode", "writing-mode", STRING),
	("xHeight", "x-height", STRING),
	("xlinkActuate", "xlink:actuate", STRING),
	("xlinkArcrole", "xlink:arcrole", STRING),
	("xlinkHref", "xlink:href", URL_ATTR_KEEP_EMPTY),
	("xlinkRole", "xlink:role", STRING),
	("xlinkShow", "xlink:show", STRING),
	("xlinkTitle", "xlink:title", STRING),
	("xlinkType", "xlink:type", STRING),
	("xmlBase", "xml:base", STRING),
	("xmlLang", "xml:lang", STRING),
	("xmlSpace", "xml:space", STRING),
	("xmlnsXlink", "xmlns:xlink", STRING),
];

/// Binary search in [`PROPS`]: `Some((attribute name, kind))`.
pub fn lookup(prop: &str) -> Option<(&'static str, u8)> {
	PROPS
		.binary_search_by(|entry| entry.0.cmp(prop))
		.ok()
		.map(|index| (PROPS[index].1, PROPS[index].2))
}

/// Style properties that take no `px` suffix for numbers (sorted).
pub static UNITLESS: [&str; 71] = [
	"MozAnimationIterationCount",
	"MozBoxFlex",
	"MozBoxFlexGroup",
	"MozLineClamp",
	"WebKitBoxFlexGroup",
	"WebkitAnimationIterationCount",
	"WebkitBoxFlex",
	"WebkitBoxOrdinalGroup",
	"WebkitColumnCount",
	"WebkitColumns",
	"WebkitFlex",
	"WebkitFlexGrow",
	"WebkitFlexPositive",
	"WebkitFlexShrink",
	"WebkitLineClamp",
	"animationIterationCount",
	"aspectRatio",
	"borderImageOutset",
	"borderImageSlice",
	"borderImageWidth",
	"boxFlex",
	"boxFlexGroup",
	"boxOrdinalGroup",
	"columnCount",
	"columns",
	"fillOpacity",
	"flex",
	"flexGrow",
	"flexNegative",
	"flexOrder",
	"flexPositive",
	"flexShrink",
	"floodOpacity",
	"fontWeight",
	"gridArea",
	"gridColumn",
	"gridColumnEnd",
	"gridColumnSpan",
	"gridColumnStart",
	"gridRow",
	"gridRowEnd",
	"gridRowSpan",
	"gridRowStart",
	"lineClamp",
	"lineHeight",
	"msAnimationIterationCount",
	"msFlex",
	"msFlexGrow",
	"msFlexNegative",
	"msFlexOrder",
	"msFlexPositive",
	"msFlexShrink",
	"msGridColumn",
	"msGridColumnSpan",
	"msGridRow",
	"msGridRowSpan",
	"msZoom",
	"opacity",
	"order",
	"orphans",
	"scale",
	"stopOpacity",
	"strokeDasharray",
	"strokeDashoffset",
	"strokeMiterlimit",
	"strokeOpacity",
	"strokeWidth",
	"tabSize",
	"widows",
	"zIndex",
	"zoom",
];

/// Whether a numeric style value of this property is written without `px`.
pub fn is_unitless(prop: &str) -> bool {
	UNITLESS.binary_search(&prop).is_ok()
}

/// HTML void elements as React knows them (sorted).
pub static VOID_ELEMENTS: [&str; 15] = [
	"area", "base", "br", "col", "embed", "hr", "img", "input", "keygen", "link", "meta", "param",
	"source", "track", "wbr",
];

/// Whether React renders this tag as `<tag/>` without an end tag.
pub fn is_void_element(tag: &str) -> bool {
	VOID_ELEMENTS.binary_search(&tag).is_ok()
}
